### PR TITLE
fix bagpipies for jest

### PR DESCRIPTION
**Pull request by sloops77**
jest tests dont work with bagpipes. the error message returned by jest's resolver (they override the standard nodejs one) is not the same as nodejs's

this simple fix makes everything work again

### CODE REVIEW

**Comment by BrunoQuaresma** [comment]
Any idea when it will be pushed?

**Comment by theganyo** [comment]
It doesn't seem like this would cause any issues, but could we get a unit test added to verify?

**Comment by BrunoQuaresma** [comment]
I use this PR code and works. I do not know why it occurs in JEST and how those changes fix it. 

@sloops77 do you can explain better the solution and how it fixes the JEST problem? 

@theganyo if it does not apply a lot of changes I think that it can be merged for now to resolve this problem in other projects that use this package as a dependency. What do you think?

**Comment by theganyo** [comment]
Yeah, we could do that. Do you need a version pushed? Or are you just looking for a merge?

**Comment by sloops77** [comment]
https://github.com/facebook/jest/pull/4203

**Comment by BrunoQuaresma** [comment]
@theganyo can be a version.

**Comment by theganyo** [comment]
Um, yeah... I forgot about the CLA requirement now. I don't think I can merge anything without that.

**Comment by sloops77** [comment]
signed it

**Comment by theganyo** [comment]
Thanks!

**Comment by BrunoQuaresma** [comment]
Thanks guys.

**Comment by sloops77** [comment]
sorry - very busy so couldnt write a test - thanks to @BrunoQuaresma for giving it a little push

**Comment by theganyo** [comment]
This is going to have to be rolled back.
https://github.com/apigee-127/bagpipes/issues/33
https://github.com/apigee-127/bagpipes/issues/34

**Pull request merged**
